AWSTemplateFormatVersion: "2010-09-09"
Description: AWS WordPress environment source bucket
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Bucket"
        - Key: CostTag
          Value: !Ref AWS::StackName
        - Key: AppManagerCFNStackKey
          Value: !Ref AWS::StackName
